version: '3.1'
services:
  db:
    image: postgres:13
    container_name: db_M7_2426
    environment:
      - POSTGRES_DB=postgres_24266
      - POSTGRES_PASSWORD=pass_postgres1
      - POSTGRES_USER=user_postgres1
    ports:
      - "5432:5432"
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_M7_2426
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: 2023_Javier.Gimenez@iticbcn.cat
      PGADMIN_DEFAULT_PASSWORD: javi123
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  local_pgdata:
  pgadmin-data: